version: '3'

services:

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-mod
      environment:
        PMA_HOST: db_moodle
        VIRTUAL_HOST: pmaMoodle.karlatic2.ml
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: pmaMoodle.karlatic2.ml
        LETSENCRYPT_EMAIL: klam9785@gmail.com
      restart: always
      expose:
       - 80
      volumes:
       - /sessions

networks:
  default:
    external:
      name: nginx-proxy
