version: '3'

services:

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-mag
      environment:
        PMA_HOST: web1_mariadb_1
        VIRTUAL_HOST: phpmyadmin3.vera1.tk
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: phpmyadmin3.vera1.tk
        LETSENCRYPT_EMAIL: jhony3256@gmail.com
      restart: always
      expose:
       - 80
      volumes:
       - /sessions

networks:
  default:
    external:
      name: nginx-proxy
