version: '3'

services:

  db_moodle:
    image: mysql:latest
    container_name: db_moodle
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "6604:3306"
    environment:
      MYSQL_DATABASE: bitnami_moodle
      MYSQL_USER: bn_moodle
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1' 
    volumes:
      - db:/var/lib/mysql

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    expose:
      - 8080
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: db_moodle
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: bn_moodle
      MOODLE_DATABASE_NAME: bitnami_moodle
      MOODLE_DATABASE_PASSWORD: examplepass
      VIRTUAL_HOST: karlatic2.ml
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: karlatic2.ml
      LETSENCRYPT_EMAIL: klam9785@gmail.com
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - db_moodle
    restart: always

volumes:
  db:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy
